Repository HJNYJ/mediDoc-v2.0, pull requests merged in 2024-04, with the labels that each got.

#2 mediDoc v2.0 DB 주소 바꾸기위해 테스트
  src/components/layout/ProgressBar.tsx
Labels: 문제 해결, 파일 수정

#4 로그인 redirection 주소 변경
  src/app/login/page.tsx
Labels: 문제 해결, 파일 수정

#6 카카오 맵 api key, next.config.mjs 수정 사항 반영
  next.config.mjs
  package.json
  src/app/login/page.tsx
  yarn.lock
Labels: 문제 해결, 파일 수정

#12 api/supabase.ts에 있는 함수 분리 및 중복되는 함수 제거
  next.config.mjs
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/bookmark.png
  src/assets/icons/bookmark_checked.png
  src/assets/icons/consult/add.png
  src/components/apply/CourseSelect.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/consult/AskForm.tsx
  src/components/home/FindHospital.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/mypage/ScrappedList.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Symptoms.tsx
  src/hooks/getConsultData.ts
  src/hooks/getHospitalData.ts
  src/hooks/getMyConsultData.ts
  src/hooks/getReservationData.ts
  src/hooks/getReviewData.ts
  src/hooks/getUserInfo.ts
  tsconfig.json
Labels: 파일 수정

#14 Feat/mainpage - 네브바 컬러 활성화, 예약내역 퍼블리싱 수정
  package.json
  src/app/consult/page.tsx
  src/assets/icons/date.png
  src/assets/icons/modal/course.png
  src/assets/icons/modal/date.png
  src/assets/icons/modal/hospital.png
  src/assets/icons/modal/reservation_id.png
  src/assets/icons/modal/status.png
  src/assets/icons/modal/subject_name.png
  src/assets/icons/previousIcon.png
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/TimeSelect.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/TopNavbar.tsx
  src/components/mypage/ReservationInfoItem.tsx
  yarn.lock
Labels: 기능 구현, 파일 수정

#16 consult form 사진 크기 제한
  next.config.mjs
  src/app/consult/page.tsx
  src/app/login/page.tsx
  src/components/consult/AskForm.tsx
  src/components/skeleton/ContainerSkeleton.tsx
Labels: 기능 구현

#17 함수 모듈화, navbar 수정, 마이페이지 예약 내역 css 수정, 실시간 상담 사진 크기 제한
  next.config.mjs
  package.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/assets/icons/bookmark.png
  src/assets/icons/bookmark_checked.png
  src/assets/icons/consult/add.png
  src/assets/icons/date.png
  src/assets/icons/modal/course.png
  src/assets/icons/modal/date.png
  src/assets/icons/modal/hospital.png
  src/assets/icons/modal/reservation_id.png
  src/assets/icons/modal/status.png
  src/assets/icons/modal/subject_name.png
  src/assets/icons/previousIcon.png
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/TimeSelect.tsx
  src/components/consult/AskForm.tsx
  src/components/home/FindHospital.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/TopNavbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ScrappedList.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Symptoms.tsx
  src/components/skeleton/ContainerSkeleton.tsx
  src/hooks/getConsultData.ts
  src/hooks/getHospitalData.ts
  src/hooks/getMyConsultData.ts
  src/hooks/getReservationData.ts
  src/hooks/getReviewData.ts
  src/hooks/getUserInfo.ts
  tsconfig.json
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#26 오류수정
  src/assets/icons/nextIcon.png
  src/components/home/SelfTestWidget.tsx
  src/components/mypage/ReservationInfoItem.tsx
Labels: 파일 수정

#28 [feat/#27] - 레이아웃 재설정, navbar 재설정
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/[userId]/page.tsx
  src/assets/icons/down.png
  src/components/apply/CourseSelect.tsx
  src/components/layout/Navbar.tsx
Labels: 파일 수정

#30 [feat] - 무한스크롤중, consult page, review page, home consult/review 퍼블리싱
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/RenderImage.tsx
  src/components/consult/UseInfiniteScroll.tsx
  src/components/consult/WriteButton.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRecent.tsx
  src/hooks/getConsultData.ts
  src/hooks/useFetchPosts.ts
Labels: 기능 구현

#35 [feat] - 사진 수정 및 UT 완료 무한스크롤 하는중
  package.json
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/PageNation.tsx
  src/components/consult/UseInfiniteScroll.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/review/ReviewRecent.tsx
  src/hooks/getConsultData.ts
  src/hooks/useFetchPosts.ts
  yarn.lock
Labels: 기능 구현, 문제 해결, 파일 수정

#38 next.config.mjs 수정
  next.config.mjs
  src/app/consult/[consultId]/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/consult/AskForm.tsx
  src/hooks/getConsultData.ts
Labels: 파일 수정

#41 로그인 redirection 주소 변경
  src/app/login/page.tsx
Labels: 파일 수정

#42 로그인 redirection 주소 변경
  src/app/login/page.tsx
Labels: 파일 수정

#43 consultImage 원래 코드로 커밋
  next.config.mjs
  src/app/consult/page.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/PageNation.tsx
  src/components/consult/useInterSectionObserver.ts
  src/types/index.ts
Labels: 문제 해결

#45 랜딩 페이지 수정
  src/components/landing/LandingPageOne.tsx
Labels: 파일 수정

#51 랜딩 페이지 수정, 회원 탈퇴 구현 중, 스피너 추가, 건강테스트 버튼 전체 활성화 등
  README.md
  package.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/ask/page.tsx
  src/app/consult/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/HospitalImage.tsx
  src/components/apply/HospitalName.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultItem.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/useInterSectionObserver.ts
  src/components/home/FindHospital.tsx
  src/components/home/MainPageReview.tsx
  src/components/home/SelfTestWidget.tsx
  src/components/home/consult/HomeConsultItem.tsx
  src/components/home/consult/HomeConsultList.tsx
  src/components/home/search/FindHospitalRegionBtn.tsx
  src/components/home/search/PopularKeyword.tsx
  src/components/home/search/RecentKeyword.tsx
  src/components/home/search/SearchBox.tsx
  src/components/landing/LandingPageOne.tsx
  src/components/layout/CheckIcons.tsx
  src/components/layout/ProgressBar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewRecent.tsx
  src/hooks/browserClient.ts
  src/hooks/getConsultData.ts
  src/hooks/useFetchPosts.ts
  src/hooks/useSession.ts
  src/types/index.ts
  tailwind.config.ts
  yarn.lock
Labels: 기능 구현, 파일 수정

#53 이미지 렌더링 시간 당기기
  src/app/consult/page.tsx
  src/components/consult/AskForm.tsx
  src/types/index.ts
Labels: 기능 구현

#55 캘린더 일자 오류 수정
  src/components/apply/ApplyPageThree.tsx
  yarn.lock
Labels: 문제 해결, 파일 수정

#58 메인페이지, 로그인페이지 변경된 부분 퍼블리싱 수정
  src/components/layout/Navbar.tsx
Labels: 문제 해결, 파일 수정

#62 빌드 에러 수정
  src/components/layout/Navbar.tsx
Labels: 문제 해결

#64 [fix/#63] 로그인 redirection 주소 변경
  src/app/login/page.tsx
Labels: 파일 수정

#65 로그인 redirection 주소 변경
  src/app/login/page.tsx
Labels: 파일 수정

#66 [feat] - mr 제거
  next.config.mjs
  src/components/home/SelfTestWidget.tsx
  src/components/map/hospitalList/HospitalItem.tsx
Labels: 파일 수정

#67 Image , margin-right 제거
  next.config.mjs
  src/components/home/SelfTestWidget.tsx
  src/components/map/hospitalList/HospitalItem.tsx
Labels: 기능 구현

#69 병원리스트 페이지 이미지 크기 조정
  src/components/map/hospitalList/HospitalItem.tsx
Labels: 파일 수정

#70 병원리스트 페이지 이미지 크기 조정
  src/components/map/hospitalList/HospitalItem.tsx
Labels: 파일 수정
