Repository HJNYJ/mediDoc-v2.0, pull requests merged in 2024-05, with the labels that each got.

#72 default 최신순으로 바꿈
  src/components/map/review/ReviewRecent.tsx
Labels: 기능 구현, 파일 수정

#73 최신순으로 Tabs
  src/components/map/review/ReviewRecent.tsx
Labels: 파일 수정

#74 consult form 리팩토링
  src/app/login/page.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/AskFormContent.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/HashTags.tsx
  src/components/consult/Input.tsx
  src/components/consult/WriteButton.tsx
Labels: 문제 해결, 파일 수정

#76 Feat/apply 파일수정
  src/app/consult/page.tsx
  src/app/login/page.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/TimeSelect.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/AskFormContent.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/consult/HashTags.tsx
  src/components/consult/Input.tsx
  src/components/consult/WriteButton.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/hospitalList/HospitalList.tsx
Labels: 파일 수정

#78 Readme 파일 수정
  README.md
  src/assets/images/architecture.png
  src/assets/images/banner.png
Labels: 파일 수정

#80 병원 관계자 마이페이지 CSS 수정
  src/app/consult/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/TimeSelect.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/AdminQuestionItem.tsx
  yarn.lock
Labels: 파일 수정
